version: '3'
services:
  echo-a:
    build: .
    command: ["-p", "8080", "-c", "Hello from a\\n"]

  echo-b:
    build: .
    command: ["-p", "8080", "-c", "Hello from b\\n"]

  nginx:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - echo-a
      - echo-b
